// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7XA7U5gQrNNYG92L3inUha8zomIlt83k',
    appId: '1:952844699752:web:5d8c06ba2bddebbeeed3dd',
    messagingSenderId: '952844699752',
    projectId: 'newapp-803ec',
    authDomain: 'newapp-803ec.firebaseapp.com',
    storageBucket: 'newapp-803ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUpxL-FJX1hgXd2VzE90QeaO2L8q3lyM',
    appId: '1:952844699752:android:c3b9dac4a10e7866eed3dd',
    messagingSenderId: '952844699752',
    projectId: 'newapp-803ec',
    storageBucket: 'newapp-803ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1dd410anDw8aG9VUnqC48YX-bDBjkStA',
    appId: '1:952844699752:ios:1c043661db774882eed3dd',
    messagingSenderId: '952844699752',
    projectId: 'newapp-803ec',
    storageBucket: 'newapp-803ec.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1dd410anDw8aG9VUnqC48YX-bDBjkStA',
    appId: '1:952844699752:ios:4f2114b2de8180c1eed3dd',
    messagingSenderId: '952844699752',
    projectId: 'newapp-803ec',
    storageBucket: 'newapp-803ec.appspot.com',
    iosBundleId: 'com.example.newsapp.RunnerTests',
  );
}
